### ISSUE TITLE
The arrow with the started class has a display issue that i'm having trouble figuring out

### ISSUE THREAD

**Issue by morebrownies** [OB1Company/easybazaar#12]
I've spent a few hours on this and haven't been able to figure it out, maybe @jjeffryes can take look when he gets a few minutes. 

Problem: The arrow is slightly different color from the rest of the div. It may have something to do with the div blinking because it doesn't happen once the blinking stops.

<img width="185" alt="screenshot 2016-10-05 10 39 36" src="https://cloud.githubusercontent.com/assets/13066886/19124893/d843ac62-8ae9-11e6-998a-f3ab8cf94e9d.png">

**Comment by jjeffryes** [comment]
It's because of the stacking order. The opacity 0.2 divs to the right are stacked on top of the arrow, so you're seeing the arrow with the next div overlaying it.

Add z-index: 1 to .progressBar div.started:not(.finished) and it'll fix it.

**Comment by morebrownies** [comment]
thanks @jjeffryes that makes sense. I'll give it a shot.
