### ISSUE TITLE
Can we set up http://ob1.io/deploy to work as well? 

### ISSUE THREAD

**Issue by morebrownies** [OB1Company/easybazaar#16]
The subdomain (http://deploy.ob1.io) is fine, but we should also make sure /deploy is working too. @tyler-smith

**Comment by hoffmabc** [comment]
Is this really needed? If so it's just a redirect but wouldn't it be better to be consistent with one?

**Comment by morebrownies** [comment]
It's more of a convenience thing. People typically don't remember if sub-domains or sub-directories are being used, so supporting both tends to be easiest for users.

A redirect would be fine.

**Comment by ghost** [comment]
@hoffmabc Could you please either set up this redirect or send me the server info ob1.io so I can do it?
